name: Build APK # 动作名称
on:
  push:
    branches: [ main ] # 监听 main 分支的推送

jobs:
  build:
    runs-on: ubuntu-latest # 运行在最新的 Ubuntu 系统上

    steps:
    - uses: actions/checkout@v3 # 检出代码

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew # 赋予 gradlew 执行权限

    - name: Build with Gradle
      run: ./gradlew assembleRelease # 执行打包命令

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: app/build/outputs/apk/release/*.apk # 指定 APK 输出路径
